---
- hosts: artiqube
  become: yes
  remote_user: ansible
  become_user: root
  
  tasks:
  - name: Download Artifactory 
    ansible.builtin.get_url:
      url: https://releases.jfrog.io/artifactory/api/gpg/key/public
      dest: /usr/share/keyrings/jfrog-keyring.asc
      
  - name: apt-key add
    ansible.builtin.shell: apt-key add /usr/share/keyrings/jfrog-keyring.asc
    
  - name: apt update
    ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: add jfrog deb repo
    ansible.builtin.shell: echo "deb https://releases.jfrog.io/artifactory/artifactory-debs jammy main" | sudo tee -a /etc/apt/sources.list

  - name: Install Artifactory
    apt: 
      name: jfrog-artifactory-oss
      state: present
      
  - name: Start Artifactory
    ansible.builtin.systemd:
      name: artifactory
      state: started
      
  - name: Install java
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Download SonarQube 
    ansible.builtin.get_url:
      url: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216-linux.zip
      dest: /opt
 
  - name: Install Unzip
    ansible.builtin.apt: 
      name: unzip
      state: present

  - name: deploiement SonarQube
    ansible.builtin.shell: unzip /opt/sonar-scanner-cli-4.5.0.2216-linux.zip 
 
  - name: Install Nano
    apt:
      name: nano
      state: present

  - name: Install Git
    apt:
      name: git
      state: present

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes
