---
- hosts: monitoring
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - alertmanager
    - prometheus
    - grafana

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter